version: '3'
services:
  web:
    build:
      context: ./ui/web
    ports:
      - "4200:80"
    networks:
      - my-network
    container_name: ehr-ui
  api_enrollment:
    build:
      context: ./api/enrollment
    ports:
      - "3002:3020"
    networks:
      - my-network
    container_name: enrollment-api
  api_notification:
    build:
      context: ./api/notification
    ports:
      - "3001:3030"
    networks:
      - my-network
    container_name: notification-api
networks:
  my-network:
